---
- name: "Systemd | Test if linger is enabled for {{ puma_user }}"
  ansible.builtin.command: "loginctl show-user {{ puma_user }}"
  changed_when: false
  failed_when: >
    'command not found' in systemd_linger_enabled_test.stderr
  register: systemd_linger_enabled_test
  become: true

- name: "Systemd | Enabled linger for {{ puma_user }}"
  ansible.builtin.command: "loginctl enable-linger {{ puma_user }}"
  changed_when: true
  become: true
  when: >
    'Failed' in systemd_linger_enabled_test.stderr

- name: Systemd | User
  become: true
  become_user: "{{ puma_user }}"
  block:
    - name: "Systemd | Ensure complete .profile"
      ansible.builtin.lineinfile:
        dest: "~/.profile"
        regexp: "^export XDG_RUNTIME_DIR="
        line: "export XDG_RUNTIME_DIR=/run/user/`id -u`"

    - name: Systemd | Ensure the user units folder exists
      ansible.builtin.file:
        path: "{{ puma_systemd_user_units }}"
        state: directory
        mode: "755"

    - name: Systemd | Create service unit
      ansible.builtin.template:
        dest: "{{ puma_systemd_unit }}"
        src: systemd.service.j2
        mode: "644"

    - name: Systemd | Enable unit at boot
      ansible.builtin.systemd_service:
        name: "{{ puma_service_name }}"
        scope: "user"
        enabled: true
