---
- name: Nginx restart
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Nginx reload
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true
