- name: Create the configurations for config.d file
  template: src=config.conf.j2 dest=/etc/nginx/conf.d/{{ item }}.conf
  with_flattened:
    - "{{ nginx_conf_d.keys() | list }}"
    - "{{ nginx_conf_extra.keys() | list }}"
  notify: nginx reload

- template: dest=/etc/nginx/conf.d/passenger.conf src=passenger.conf.j2
  notify: nginx reload
  name: "Create /etc/nginx/conf.d/passenger.conf main config for serverwide settings"

- template: dest=/etc/nginx/sites-available/{{nginx_config_file}} src=site.conf.j2
  notify: nginx reload

- file: src=/etc/nginx/sites-available/{{nginx_config_file}} dest=/etc/nginx/sites-enabled/{{app_name}} state=link owner=root group=root
  notify: nginx reload

- name: Create nginx default config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: nginx reload
