---
- name: Debian | Restart required
  when: rails_unicorn_restart.stat.exists
  become: true
  become_user: "{{ unicorn_user }}"
  block:
    - name: Debian | Remove RAILS_APP_RESTART_PATH
      ansible.builtin.file:
        path: "{{ RAILS_APP_RESTART_PATH }}"
        state: absent

    - name: Debian | Upstart | Restart
      ansible.builtin.shell: "{{ profile }}'restart unicorn || start unicorn'"
      changed_when: true
      when: unicorn_service_type == 'upstart'

    - name: Debian | Systemd | Restart
      ansible.builtin.systemd_service:
        name: "{{ unicorn_service_name }}"
        scope: "user"
        state: restarted
