---
- name: Red Hat | Install EPEL repo
  ansible.builtin.dnf:
    name: "{{ rbenv_epel_repo }}"
    update_cache: true

- name: Red Hat | Install dependencies
  ansible.builtin.dnf:
    pkg: "{{ rbenv_package_names }}"
    update_cache: true
