---
# Packages required for postgresql gem
- name: Redhat
  ansible.builtin.include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Debian
  ansible.builtin.include_tasks: Debian.yml
  when: ansible_os_family == "Debian"
