---
- name: Check GPG keys
  ansible.builtin.command: 'gpg --list-keys {{ item }}'
  failed_when: false
  changed_when: false
  register: rvm_gpg_keys_checks
  become: true
  become_user: "{{ rvm_user }}"
  loop: "{{ rvm_gpg_keys_list }}"

- name: Import GPG keys
  ansible.builtin.command: 'gpg --keyserver {{ rvm_gpg_key_server }} --recv-keys {{ rvm_gpg_keys_list[index] }}'
  ignore_errors: true
  register: rvm_import_gpg_keys_result
  become: true
  become_user: "{{ rvm_user }}"
  changed_when: true
  when: item.rc != 0
  loop: "{{ rvm_gpg_keys_checks.results }}"
  loop_control:
    index_var: index

- name: Check failed
  ansible.builtin.set_fact:
    rvm_gpg_failed: true
  when: item.item.rc != 0
  loop: "{{ rvm_import_gpg_keys_result.results }}"

- name: Alternative GPG keys
  ansible.builtin.shell:
    cmd: >
      set -o pipefail
      && curl -sSL {{ rvm_gpg_key_alternative_url }} | gpg --import -
    executable: /bin/bash
  become: true
  become_user: "{{ rvm_user }}"
  changed_when: true
  when: rvm_gpg_failed is defined and rvm_gpg_failed
