---
- name: Packages
  ansible.builtin.apt:
    name: "{{ rvm_packages + rvm_custom_packages + rvm_build_packages | flatten | list | unique }}"
    update_cache: true
    state: present
    cache_valid_time: 86400

- name: GPG
  ansible.builtin.include_tasks: gpg_keys.yml
  when: rvm_gpg_keys != ''

- name: Run as RVM user
  become: true
  become_user: "{{ rvm_user }}"
  block:
    - name: Install RVM
      # note: we need the pipe to work here
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: >
          set -o pipefail
          && curl -L https://get.rvm.io | bash -s stable --autolibs=disable --auto-dotfiles
        creates: ~/.rvm/bin/rvm

    - name: Build OpenSSL by RVM
      ansible.builtin.command:
        cmd: "~/.rvm/bin/rvm pkg install openssl"
        creates: ~/.rvm/usr/lib/libssl.so
      when: rvm_pkg_openssl

    - name: Ruby versions
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -e
          set -o pipefail
          ~/.rvm/bin/rvm list strings | if ! grep "^ruby-{{ item }}" ; then
            ~/.rvm/bin/rvm install \
              {{ '--default' if item == rvm_default else '' }} \
              {{ '--with-openssl-dir=$HOME/.rvm/usr' if rvm_pkg_openssl }} \
              {{ item }}
            echo "ANSIBLE_CHANGED"
          else
            {% if item == rvm_default %}
              ~/.rvm/bin/rvm current | if ! grep "^ruby-{{ item }}" ; then
                ~/.rvm/bin/rvm default ruby-{{ item }}
                echo "ANSIBLE_CHANGED"
              fi
            {% else %}
              true
            {% endif %}
          fi
      register: ruby_install_result
      changed_when: ruby_install_result.stdout is defined and 'ANSIBLE_CHANGED' in ruby_install_result.stdout
      loop: "{{ rvm_rubies + [rvm_default] | flatten }}"

    - name: Facts
      ansible.builtin.set_fact:
        RUBY_PREFIX: "~/.rvm/bin/rvm default do "

    - name: Ruby Path
      ansible.builtin.command:
        cmd: "{{ RUBY_PREFIX }} rvm gemdir"
      register: ruby_rvm_ruby_path_result
      changed_when: false

    - name: Facts
      ansible.builtin.set_fact:
        RUBY_BIN: "{{ ruby_rvm_ruby_path_result.stdout_lines[0] }}/wrappers/ruby"

    - name: Gem Version
      ansible.builtin.command:
        cmd: "{{ RUBY_PREFIX }} gem --version"
      register: ruby_rvm_gem_version_result
      changed_when: false

    - name: Gem Update System
      ansible.builtin.command:
        cmd: "{{ RUBY_PREFIX }} gem update --system {{ rvm_gem_version }}"
      when: rvm_gem_version != '' and rvm_gem_version != ruby_rvm_gem_version_result.stdout
      register: ruby_rvm_gem_update_system_result
      changed_when: >
        "Aborting" not in ruby_rvm_gem_update_system_result.stdout

    - name: Install gems
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -e
          set -o pipefail
          {{ RUBY_PREFIX }} gem list | if ! grep "^{{ item | split(':') | first }} " ; then
            {{ RUBY_PREFIX }} gem install {{ item | split(':') | first }} -v {{ item | split(':') | last | default('>=0') }}
          fi
      register: ruby_rvm_gem_install_result
      changed_when: >
        ("Successfully installed ITEM" | regex_replace('ITEM', item)) in ruby_rvm_gem_install_result.stdout
      loop: "{{ rvm_install_gems | flatten }}"
