FROM ubuntu:18.04

# Install Ansible
RUN apt-get update && apt-get install -y \
  software-properties-common \
  git \
	python \
  curl \
  sudo \
  apt-transport-https \
  locales \
&& apt-add-repository -y ppa:ansible/ansible \
&& apt-get update && apt-get install -y ansible

RUN wget "https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py" -O /usr/bin/systemctl && \
	chmod +x /usr/bin/systemctl && \
	mkdir /run/systemd/system/

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

CMD ["/usr/bin/systemctl"]
