---
- name: PPA
  when: nginx_install == "ppa"
  block:
    - name: Debian | PPA Repo
      ansible.builtin.apt_repository:
        repo: "{{ nginx_ppa_repo }}"

- name: Offical Site
  when: nginx_install == "official"
  block:
    - name: Debian | GPG
      ansible.builtin.apt:
        name:
          - "gpg"
          - "apt-transport-https"
          - "ca-certificates"
        state: latest
        update_cache: true
        cache_valid_time: 3600

    - name: Debian | Add official key
      ansible.builtin.apt_key:
        keyserver: "{{ item }}"
        id: "{{ nginx_official_key_id }}"
      loop: "{{ nginx_official_key_servers }}"
      retries: 2
      delay: 1

    - name: Install | Add repo
      ansible.builtin.apt_repository:
        repo: "{{ nginx_official_repo }}"

- name: Debian | Packages
  ansible.builtin.apt:
    name: "{{ nginx_package_names }}"
    update_cache: true
    state: latest
    cache_valid_time: 86400

- name: Debian | Enable nginx
  ansible.builtin.service:
    name: "{{ nginx_service_name }}"
    enabled: true
  notify:
    - Restart nginx
