---
- name: PPA
  when: nginx_install == "ppa"
  block:
    - name: Debian | PPA Repo
      ansible.builtin.apt_repository:
        repo: "{{ nginx_ppa_repo }}"

- name: Offical Site
  when: nginx_install == "official"
  block:
    - name: Debian | GPG
      ansible.builtin.apt:
        name:
          - "gpg"
          - "apt-transport-https"
          - "ca-certificates"
          - "python3-debian"
        state: latest
        update_cache: true
        cache_valid_time: 3600

    - name: Debian | Add repo
      ansible.builtin.deb822_repository:
        name: NGINX
        types: deb
        uris: ["{{ nginx_official_repo_uri }}"]
        suites: ["{{ ansible_lsb.codename }}"]
        components: [nginx]
        architectures: [amd64]
        signed_by: "{{ nginx_official_key_url }}"

- name: Debian | Packages
  ansible.builtin.apt:
    name: "{{ nginx_package_names }}"
    update_cache: true
    state: latest
    cache_valid_time: 86400

- name: Debian | Enable nginx
  ansible.builtin.service:
    name: "{{ nginx_service_name }}"
    enabled: true
  notify: Restart nginx
