---
- name: RedHat | Install nginx.org repo rpm
  ansible.builtin.dnf:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm

- name: RedHat | Install packages
  ansible.builtin.dnf:
    pkg: "{{ nginx_package_names }}"
    update_cache: true
    state: latest

- name: RedHat | Reload systemd configs
  ansible.builtin.shell:
    cmd: "warn=no && systemctl daemon-reload"
  changed_when: false

- name: RedHat | Enable nginx
  ansible.builtin.service:
    name: "{{ nginx_service_name }}"
    enabled: true
