---
- name: Enable ForwardAgent
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/ssh_config"
    line: "    ForwardAgent yes"
    regexp: "^\\s*ForwardAgent"
    create: true
    mode: "644"

- name: Sudoer forward_ssh_agent
  ansible.builtin.template:
    src: "forward_ssh_agent.j2"
    dest: "/etc/sudoers.d/forward_ssh_agent"
    mode: "644"
