---
#
# enables upstart user jobs
#
- name: Precise
  ansible.builtin.include_tasks: precise.yml
  when: (ansible_distribution == 'Ubuntu') and (ansible_lsb.major_release|int <= 13)

- name: Create ~/.init folder
  ansible.builtin.file:
    path: ~/.init
    state: directory
    mode: "755"
  become: true
  become_user: "{{ item }}"
  loop: "{{ users }}"
  when: ansible_os_family == "Debian"

- name: Trusty
  ansible.builtin.include_tasks: trusty.yml
  when: (ansible_distribution == 'Ubuntu') and (ansible_lsb.major_release|int >= 14)
