---
- name: Precise Allow
  ansible.builtin.template:
    src: "Upstart.conf"
    dest: "/etc/dbus-1/system.d/Upstart.conf"
    force: true
    mode: "644"

- name: Precise Autostart
  ansible.builtin.template:
    src: "load_user_jobs.conf"
    dest: "/etc/init/load_user_jobs.conf"
    mode: "644"
