---
- name: Upstart
  ansible.builtin.include_tasks: "upstart.yml"
  when: ansible_service_mgr != "systemd"

- name: Systemd
  ansible.builtin.include_tasks: "systemd.yml"
  when: ansible_service_mgr == "systemd"
