- name: Tell sidekiq to not accept new work
  ansible.builtin.command: 'sudo -n /bin/systemctl kill -s USR1 {{ sidekiq_job_name }}'
  failed_when: false
  changed_when: true

- name: 'Make sure sidekiq is started at the end'
  ansible.builtin.command: '/bin/true'
  notify: Restart sidekiq (systemd)
  changed_when: true
