---
- name: Tell sidekiq to not accept new work
  ansible.builtin.command: "{{ profile }}'reload {{ sidekiq_job_name }}'"
  failed_when: false
  changed_when: true

- name: 'Make sure sidekiq is started at the end'
  ansible.builtin.command: '/bin/true'
  notify: Restart sidekiq (upstart)
  changed_when: true
