---
- name: Debian | Add repo key
  apt_key:
    url: "{{ postgresql_apt_key }}"

- name: Debian | Add repo
  apt_repository:
    repo: "{{ postgresql_apt_repo }}"

- name: Debian | Packages
  apt:
    pkg: "{{ [postgresql_packages, postgresql_python_packages] | flatten }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400
