---
- name: Debian | GPG
  ansible.builtin.apt:
    name:
      - gpg
      - apt-transport-https
      - ca-certificates
      - python3-debian
      - locales
    state: latest
    update_cache: true
    cache_valid_time: 86400

- name: Ensure locale is selected
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    state: present
    regexp: "^#\\s*{{ postgresql_locale }}.{{ postgresql_encoding }}.*$"
    line: "{{ postgresql_locale }}.{{ postgresql_encoding }} {{ postgresql_encoding }}"
  register: locale_gen_result

- name: Generate locale if changed
  ansible.builtin.command: locale-gen
  changed_when: true
  when: locale_gen_result.changed and true

- name: Install | Add repo
  ansible.builtin.deb822_repository:
    name: Postgresql
    types: deb
    uris: ["{{ postgresql_apt_url }}"]
    suites: ["{{ ansible_lsb.codename }}-pgdg"]
    components: [main]
    architectures: [amd64]
    signed_by: "{{ postgresql_apt_key }}"
  register: repo_result

# note: apt_key no longer works
# - name: Debian | Add repo key
#   ansible.builtin.apt_key:
#     url: "{{ postgresql_apt_key }}"

# - name: Debian | Add repo
#   ansible.builtin.apt_repository:
#     repo: "{{ postgresql_apt_repo }}"

- name: Debian | Packages
  ansible.builtin.apt:
    name: "{{ postgresql_packages + postgresql_python_packages | flatten }}"
    state: latest
    update_cache: "{{ repo_result.changed | bool }}"
