---
- name: RedHat | Get archive index stat info
  ansible.builtin.stat:
    path: "/var/cache/yum/pg-{{ postgresql_version }}.html"
  register: postgresql_repo_index_result

- name: RedHat | Get archive index
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail
      && curl -sS {{ postgresql_org_archive_dir }} > {{ postgresql_repo_index }}
    executable: /bin/bash
  when: not postgresql_repo_index_result.stat.exists
    or postgresql_repo_index_result.stat.mtime + 604800 < (ansible_date_time.epoch | int)
  changed_when: true

- name: RedHat | Get current repo rpm filename
  ansible.builtin.shell:
    cmd: >
      set -o pipefail
      && grep -oE "pgdg-centos{{ postgresql_org_version }}[^\"]+\.rpm" {{ postgresql_repo_index }} | tail -1
    executable: /bin/bash
  register: postgresql_repo_rpm_filename
  changed_when: false

- name: RedHat | Ensure postgresql.org repo rpm is up-to-date
  ansible.builtin.get_url:
    url: "{{ postgresql_org_archive_dir }}{{ postgresql_repo_rpm_filename.stdout }}"
    dest: "/var/cache/yum/{{ postgresql_repo_rpm_filename.stdout }}"
    mode: "644"

- name: RedHat | Install postgresql.org Redhat repo rpm
  ansible.builtin.dnf:
    name: "/var/cache/yum/{{ postgresql_repo_rpm_filename.stdout }}"

- name: RedHat | Install packages
  ansible.builtin.dnf:
    pkg: "{{ [postgresql_packages, postgresql_python_packages] | flatten }}"
    state: latest
    update_cache: true

- name: RedHat | Initialize PostgreSQL
  ansible.builtin.command: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql{{ postgresql_org_version }}-setup initdb"
  args:
    creates: "{{ postgresql_data_path }}/base"

- name: RedHat | Ensure PostgreSQL-server is running
  ansible.builtin.service:
    name: "{{ postgresql_service }}"
    state: started
    enabled: true
