---
- name: "Systemd | Test if linger is enabled for {{ webrick_user }}"
  shell: "loginctl show-user {{ webrick_user }}"
  changed_when: false
  failed_when: >
    'command not found' in systemd_linger_enabled_test.stderr
  register: systemd_linger_enabled_test
  become: true

- name: "Systemd | Enabled linger for {{ webrick_user }}"
  shell: "loginctl enable-linger {{ webrick_user }}"
  changed_when: true
  become: true
  when: >
    'Failed' in systemd_linger_enabled_test.stderr

- become_user: "{{ webrick_user }}"
  block:
    - name: "Systemd | Ensure complete .profile"
      lineinfile:
        dest: "~/.profile"
        regexp: "^export XDG_RUNTIME_DIR="
        line: "export XDG_RUNTIME_DIR=/run/user/`id -u`"

    - name: Systemd | Ensure the user units folder exists
      file:
        path: "{{ webrick_systemd_user_units }}"
        state: directory

    - name: Systemd | Create service unit
      template:
        dest: "{{ webrick_systemd_unit }}"
        src: systemd.service.j2

    - name: Systemd | Enable unit at boot
      shell: "/bin/bash -lc -- 'systemctl --user enable {{ webrick_service_name }}.service'"
      register: enable_unit_result
      changed_when: >
        'Created' in enable_unit_result.stderr
