---
- name: Restart sidekiq (upstart)
  ansible.builtin.shell: "{{ profile }}'restart {{ sidekiq_job_name }} || start {{ sidekiq_job_name }}'"
  changed_when: true

- name: Restart sidekiq (systemd)
  ansible.builtin.command: 'sudo -n /bin/systemctl restart {{ sidekiq_job_name }}'
  changed_when: true
