#
# Define a release id, extract it from git and construct shared and custom folders
#
---
- name: Facts
  ansible.builtin.include_tasks: facts.yml

- name: Git
  ansible.builtin.include_tasks: git.yml
  when: rails_release_strategy == 'git'

- name: Empty
  ansible.builtin.include_tasks: empty.yml
  when: rails_release_strategy == 'empty'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Create custom folders
  ansible.builtin.file:
    path: "{{ RAILS_APP_RELEASE_PATH }}/{{ item }}"
    state: directory
    mode: "755"
  loop: "{{ rails_deploy_custom_create_folders | flatten }}"

- name: Provide Rails configuration files
  ansible.builtin.copy:
    dest: "{{ RAILS_APP_SHARED_PATH }}/{{ item.file }}"
    content: |
      {% if item.yaml is defined %}
      ---
      # {{ ansible_managed }}
      {{ item.yaml | to_nice_yaml }}
      {% elif item.plain is defined %}
      {{ item.plain }}
      {% else %}
      {{ false | mandatory('Only yaml or plain configurations are supported!') }}
      {% endif %}
    owner: "{{ app_user }}"
    mode: "0600"
  loop: "{{ rails_provisioned_files }}"

- name: Shared Folders
  ansible.builtin.include_tasks: "shared_folders.yml"
