---
- name: Create shared folders
  file:
    path: "{{ RAILS_APP_SHARED_PATH }}/{{ item }}"
    state: directory
  with_flattened:
  - "{{ rails_deploy_shared_folders }}"
  - "{{ rails_deploy_custom_shared_folders }}"
  - "{{ rails_deploy_custom_shared_webpacker_folders if rails_webpacker else [] }}"

- name: Link shared folders
  file:
    src: "{{ RAILS_APP_SHARED_PATH }}/{{ item }}"
    path: "{{ RAILS_APP_RELEASE_PATH }}/{{ item }}"
    state: link
    force: true
  with_flattened:
  - "{{ rails_deploy_shared_folders }}"
  - "{{ rails_deploy_custom_shared_folders }}"
  - "{{ rails_deploy_custom_shared_webpacker_folders if rails_webpacker else [] }}"

- name: Link shared files
  file:
    src: "{{ RAILS_APP_SHARED_PATH }}/{{ item }}"
    path: "{{ RAILS_APP_RELEASE_PATH }}/{{ item }}"
    state: link
    force: true
  with_flattened:
  - "{{ rails_shared_files }}"

- name: Link provisioned files
  file:
    src: "{{ RAILS_APP_SHARED_PATH }}/{{ item.file }}"
    path: "{{ RAILS_APP_RELEASE_PATH }}/{{ item.file }}"
    state: link
    force: true
  with_flattened:
  - "{{ rails_provisioned_files }}"
