---
- name: Folders | Base
  ansible.builtin.file:
    path: "{{ RAILS_APP_RELEASE_PATH }}"
    state: directory
    mode: "755"

- name: Folders | Create
  ansible.builtin.file:
    path: "{{ RAILS_APP_RELEASE_PATH }}/{{ item }}"
    state: directory
    mode: "755"
  loop: "{{ rails_vagrant_create_folders + rails_vagrant_custom_create_folders | flatten }}"
