#
# Create a vagrant release from the vagrant mount
#
# As windows vagrant mounts do not support links to the shared folder,
# we have link to parts
#
---
- name: Facts
  ansible.builtin.include_tasks: "facts.yml"
- name: Folders
  ansible.builtin.include_tasks: "folders.yml"
- name: Links
  ansible.builtin.include_tasks: "links.yml"
- name: Shared Folders
  ansible.builtin.include_tasks: "../../create-release/tasks/shared_folders.yml"
