---
- name: Install | GPG
  ansible.builtin.apt:
    name:
      - "gpg"
      - "apt-transport-https"
      - "ca-certificates"
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Configure the Yarn APT key
  ansible.builtin.apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn repository
  ansible.builtin.apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present

- name: Install Yarn
  ansible.builtin.apt:
    name: yarn
    state: present
