---
- name: Copy script
  ansible.builtin.copy:
    src: "git-credential-helper-env.sh"
    dest: "/usr/local/bin/git-credential-env"
    mode: "u=rwx,go=rx"

- name: Configure script
  community.general.git_config:
    name: "credential.helper"
    value: "env"
    scope: "{{ git_credential_scope }}"
    repo: "{{ git_credential_repo_path }}"
  become: true
  become_user: "{{ git_credential_config_user }}"
