---
- name: 'Create systemd {{ mailroom_job_name }}'
  ansible.builtin.template:
    dest: /lib/systemd/system/{{ mailroom_job_name }}.service
    src: mailroom.service.j2
    mode: "644"
  notify: Start service

- name: "Enable passwordless sudo for job control of {{ mailroom_job_name }}"
  ansible.builtin.template:
    src: 'sudoers.j2'
    dest: '/etc/sudoers.d/{{ mailroom_job_name }}'
    mode: "644"
