---
- name: Install | gpg
  ansible.builtin.apt:
    name:
      - "gpg"
      - "apt-transport-https"
      - "ca-certificates"
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Install | add key
  ansible.builtin.apt_key:
    keyserver: "{{ apache_passenger_key_server }}"
    id: "{{ apache_passenger_key_id }}"

- name: Install | add repo
  ansible.builtin.apt_repository:
    repo: "{{ apache_passenger_apt_repo }}"

- name: Install | packages
  ansible.builtin.apt:
    pkg: "{{ apache_passenger_package }}"
    state: "{{ apache_passenger_state }}"
    update_cache: true
    cache_valid_time: 3600
  notify: Restart apache

- name: Install | enable module
  community.general.apache2_module:
    name: "{{ apache_passenger_mod }}"
  notify: Restart apache
