---
- name: "Systemd | Test if linger is enabled for {{ unicorn_user }}"
  ansible.builtin.command: "loginctl show-user {{ unicorn_user }}"
  changed_when: false
  failed_when: >
    'command not found' in systemd_linger_enabled_test.stderr
  register: systemd_linger_enabled_test
  become: true

- name: "Systemd | Enabled linger for {{ unicorn_user }}"
  ansible.builtin.command: "loginctl enable-linger {{ unicorn_user }}"
  changed_when: true
  become: true
  when: >
    'Failed' in systemd_linger_enabled_test.stderr

- name: "Systemd | User service"
  become: true
  become_user: "{{ unicorn_user }}"
  block:
    - name: "Systemd | Ensure complete .profile"
      ansible.builtin.lineinfile:
        dest: "~/.profile"
        regexp: "^export XDG_RUNTIME_DIR="
        line: "export XDG_RUNTIME_DIR=/run/user/`id -u`"

    - name: Systemd | Ensure the user units folder exists
      ansible.builtin.file:
        path: "{{ unicorn_systemd_user_units }}"
        state: directory
        mode: "755"

    - name: Systemd | Create service unit
      ansible.builtin.template:
        dest: "{{ unicorn_systemd_unit }}"
        src: systemd.service.j2
        mode: "644"

    - name: Systemd | Enable unit at boot
      ansible.builtin.command: "/bin/bash -lc -- 'systemctl --user enable {{ unicorn_service_name }}.service'"
      register: enable_unit_result
      changed_when: >
        'Created' in enable_unit_result.stderr
