---
- name: Restart exists
  when: rails_webrick_restart.stat.exists
  block:
    - name: Debian | Remove RAILS_APP_RESTART_PATH
      ansible.builtin.file:
        path: "{{ RAILS_APP_RESTART_PATH }}"
        state: absent

    - name: Debian | Upstart | Restart
      ansible.builtin.shell: "{{ profile }}'restart webrick || start webrick'"
      changed_when: true
      when: webrick_service_type == 'upstart'

    - name: Debian | Systemd | Restart
      ansible.builtin.command: "{{ profile }}'systemctl --user restart {{ webrick_service_name }}.service'"
      changed_when: true
      when: webrick_service_type == 'systemd'
