---
- name: Restart exists
  when: rails_webrick_restart.stat.exists
  become: true
  become_user: "{{ webrick_user }}"
  block:
    - name: Debian | Remove RAILS_APP_RESTART_PATH
      ansible.builtin.file:
        path: "{{ RAILS_APP_RESTART_PATH }}"
        state: absent

    - name: Debian | Upstart | Restart
      ansible.builtin.shell: "{{ profile }}'restart webrick || start webrick'"
      changed_when: true
      when: webrick_service_type == 'upstart'

    - name: Debian | Systemd | Restart
      ansible.builtin.systemd_service:
        name: "{{ webrick_service_name }}"
        scope: "user"
        state: restarted
      when: webrick_service_type == 'systemd'
