---
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Check for Restart
  ansible.builtin.stat:
    path: "{{ RAILS_APP_RESTART_PATH }}"
  register: rails_webrick_restart

- name: Redhat
  ansible.builtin.include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Debian
  ansible.builtin.include_tasks: Debian.yml
  when: ansible_os_family == "Debian"
