---
- name: Run Rake task
  ansible.builtin.command: "{{ profile }}'bundle exec rake {{ rake_task }}'"
  args:
    chdir: "{{ RAILS_APP_RELEASE_PATH }}"
  changed_when: true
  run_once: "{{ rake_task_run_once }}"
