---
- name: "Create systemd service {{ sidekiq_job_name }}"
  ansible.builtin.template:
    src: sidekiq.service.j2
    dest: /lib/systemd/system/{{ sidekiq_job_name }}.service
    mode: "644"
  notify: Start service

- name: "Enable passwordless sudo for job control of {{ sidekiq_job_name }}"
  ansible.builtin.template:
    src: 'sudoers.j2'
    dest: '/etc/sudoers.d/{{ sidekiq_job_name }}'
    mode: "755"
