- name: Sidekiq upstart script
  template:
    src: "sidekiq.conf.j2"
    dest: "{{ sidekiq_upstart_conf }}"
  become: true
  become_user: "{{ sidekiq_upstart_user }}"

- name: sidekiq config
  template:
    src: "sidekiq.yml.j2"
    dest: "{{ sidekiq_config_file }}"
  become: true
  become_user: "{{ sidekiq_upstart_user }}"
